### ISSUE TITLE
Async load leeds to UnsatisfiedLinkError: No implementation found

### ISSUE THREAD

**Issue by alhah** [KeepSafe/ReLinker#45]
https://github.com/KeepSafe/ReLinker/blob/e0a78d947d34040887bb63eccd4431466f95fc82/relinker/src/main/java/com/getkeepsafe/relinker/ReLinkerInstance.java#L138

I used ReLinker.LoadListener to loadLibrary, but if I call native method immediately,  it would be fail.

**Comment by benjamin-bader** [comment]
Since you linked the `new Thread` line, and didn't give any other details, I'm guessing that you are passing in a `ReLinker.LoadListener` to the `loadLibrary` call.  By providing a listener, you're triggering an asynchronous load (which is usually a good thing!).  You'll need to defer any native calls until _after_ the listener gets invoked.

Alternately, you can just pass `null` instead of a listener, and loading will by synchronous... on the main thread.

**Comment by alhah** [comment]
Is it necessary to use async load here? It's very easy to make mistake here, and there seems no benefit.

**Comment by benjamin-bader** [comment]
Maybe, depending on what you're loading, when you're loading it, and how much you value minimizing app startup time.  If loading libraries synchronously doesn't slow you down too much, then do it.

Async is there for those cases where sync is too slow; it's up to you which you need to use.

**Comment by alhah** [comment]
I got it,  thank you. I think maybe you should comment LoadListener more clearly that it's just useful for async load occasion.
