### ISSUE TITLE
Question: What is the difference between ReLinker and SoLoader?

### ISSUE THREAD

**Issue by maxim-pandra** [KeepSafe/ReLinker#76]
ReLinker is "A robust native library loader for Android"

SoLoader is a native code loader for Android. It takes care of unpacking your native libraries and recursively loads dependencies on platforms that don't support that out of the box.

What should I choose for native library loading? What is the difference between the two?

**Comment by benjamin-bader** [comment]
They originated as two different libraries that approached the same problem in different ways.  Relinker was the first to properly handle transitive dependencies by parsing elf files, but I believe SoLoader has grown that capability by now.

Basically the difference is down to the internal approach.  SoLoader attempts to hook in to the native machinery underpinning `System.loadLibrary`, while ReLinker does its fixes at a higher level, without reflecting in to the runtime.  Each approach has its merits, but ReLinker ends up being a lighter dependency, if only by a bit.  Certainly it's easier to build, hack on, and debug relinker, due to SoLoader using Buck for its build system - though since you're asking which library to _use_, that's probably not so relevant to you :)

As far as I'm aware, both libraries do the job just fine.

**Comment by philippb** [comment]
Created a wiki page and added this as the first FAQ
https://github.com/KeepSafe/ReLinker/wiki
